### ISSUE TITLE
BUG: 2107 error is received when trying to add the lineup for USA-OTA-27244 in tv_grab_zz_sdjson_sqlite

### ISSUE THREAD

**Issue by mamarley** [SchedulesDirect/JSON-Service#74]
When I try to add the USA-OTA-27244 lineup, it gives me the error message "2107 The lineup is being generated on the server. Please retry.".  Trying the nearby 27515 zipcode works fine.

**Comment by rkulagowski** [comment]
I've checked the server, and I'm seeing a valid lineup:

"metadata":{"lineup":"USA-OTA-27244","modified":"2017-10-15T01:13:22Z","transport":"Antenna"}}

So that timestamp was about 3h ago relative to now (2017-10-14 @ 23:28P CDT / 2017-01-15 @ 04:28 UTC).  Is this particular error still happening "now"?

**Comment by mamarley** [comment]
Thanks, it works now!
